[package]
name = "steamlink-openrp"
version = "0.1.0"
authors = ["John Bellone <jbellone@fastmail.com>"]

[[bin]]
name = "openrp"
path = "src/main.rs"

[dependencies]
clap = "2.26.2"
env_logger = "0.4.3"
error-chain = "0.11"
log = "0.3.8"
sdl2 = "0.30"
time = "0.1.38"
